### ISSUE TITLE
Work on OSS Project Checklist

### ISSUE THREAD

**Issue by cjtu** [cjtu/craterpy#3]
# OSS Project Checklist

A checklist from https://github.com/scriptnull/oss-checklist to be a guide future open-source development of craterpy.

## Pre-checks
- [ ] Able to explain your project in a tweet ?
- [x] Choose a name for the project
- [x] Check if domain name / App name is available ?
- [x] List and learn tools required for the project
- [ ] Prepare mock-up and one page design document, if needed to explain to collaborators
- [ ] List previous / similar implementations and learn from them
- [ ] Start a blog post to document the journey ( if time permits ) Mention idea + helpful resources.
- [ ] Ask if project could be solved in a modular way by dividing into sub-problems and creating a separate project for the sub-problems.

## Project Creation
- [x] Create a Repository in Github
- [x] Create a README.rst (check below for more)
- [x] Create a LICENSE file (choose one before)
- [x] Create a CONTRIBUTING.rst
- [x] Create a .gitignore

## README.md Checklist
- [x] Title
- [ ] Logo
- [x] Badges
- [x] Description
- [x] Prerequisite for using software ( if any )
- [x] Install
- [ ] Example Usage
- [ ] Screenshots and GIFs
- [ ] Contributors
- [ ] Attributions ( mention 3rd party libs used etc. )

## Coding Phase
- [ ] Install required developer tools
    - [x] Compiler
    - [x] Linter
    - [x] Build Tools
    - [ ] Other
- [x] Organize files and folders that will help readers to find code easily
- [x] Basic code complete
- [x] Write tests and keep watch on code coverage
- [ ] Setup CI
    - [x] Setup CI on Linux (Travis CI)
    - [x] Setup CI on Windows (AppVeyor)
    - [ ] Setup CI on OS X (tricky with anaconda, explore further)
- [x] Host the documentation of the code on ReadTheDocs
- [x] Use Github issues ( or other tools ) for tracking backlogs
- [x] Encourage OSS culture by having labels like "help wanted" "easy-to-contribute" etc.
- [ ] Contribute to other OSS projects on which the current project is dependent on ( if possible )
    - File bug reports
    - Improve docs
    - Suggest feature
    - Learn by reading code

## Release Phase
- [x] Package software in CI or manually in local
- [x] Publish in registries (PyPI, conda-forge, etc.)
- [x] Create the release version, description, link for downloading the release etc. in release page ( example: Github release page)

## Post-release
- [ ] Publish the blog post
- [ ] [Tweet](https://twitter.com/)
- [ ] [Hackernews](https://news.ycombinator.com/)
- [ ] [Product Hunt](http://producthunt.com/)
- [ ] Send PR to `awesome-*` github repository
- [ ] [Reddit](https://www.reddit.com)
- [ ] [Hashnode](https://hashnode.com/)
- [ ] [Linkedin](https://www.linkedin.com/)
- [ ] Edit Wikipedia pages (if related)
- [ ] Prepare slides and give talks (if possible)

**Comment by cjtu** [comment]
Most of this will be checked off with v1.0, and most of what isn't, is not relevant anymore
