### ISSUE TITLE
Improve Docstrings

### ISSUE THREAD

**Issue by cjtu** [cjtu/craterpy#4]
# Docstrings
Docstings are important for auto-building API docs for craterpy. We use the numpy style guide which has a great summary [here](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt)

## TODO:
- [ ] Give all modules, classes, functions, and methods a docstring (min 1 line description).
- [ ] "Attributes" and "methods" sections for all classes
- [ ] "Parameters" section for all functions, methods (where applicable)
- [ ] "Returns" section for all functions, methods (where applicable)
- [ ] "Raises" section if Exceptions are raised
- [ ] "Examples" section and update existing examples
